version: 2.1

workflows:
  test-deploy:
    jobs:
      - test

jobs:
  test:
    machine: true
    resource_class: patel-viraj/linux
   # docker:
    #  - image: cimg/node:14.13.0
    steps:
      - run: echo "Hi I'm on Runners!"
#       - checkout
#       - run: node --version
#       - run: npm i
#       - run: pm2 start app.js
