version: 2.1

workflows:
  test-deploy:
    jobs:
      - test
       - docker_hub_build_push_image:
          requires:
            - test
      - aws-ecr/build_and_push_image:
          region: us-east-1
          account-url: ${AWS_ECR_ACCOUNT_URL}
          repo: ${CIRCLE_PROJECT_REPONAME}
          tag: ${CIRCLE_BUILD_NUM}
          requires:
            - test
            
  jobs:
    test:
      docker:
        - image: circleci/python:2.7.14
      steps:
        - checkout
        - run: 
            name: Build and push Docker image to ECR
            command: |
                aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/l4t9p4k5          

# jobs:
#   test:
#     docker:
#       - image: cimg/node:14.13.0
#     steps:
#       - checkout
#       - run: 
#           name: Install dependences
#           command: scp -r -o StrictHostKeyChecking=no * ubuntu@54.83.108.237:/home/ubuntu/ 
#       - run: |
#             ssh -o StrictHostKeyChecking=no ubuntu@54.83.108.237 \
#             npm i      
#       - run: |
#             ssh -o StrictHostKeyChecking=no ubuntu@54.83.108.237 \
#             pm2 restart app.js
