version: 2.1

workflows:
  test-deploy:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: cimg/node:14.13.0
    steps:
      - checkout
      - run: 
          name: Install dependences
          command: npm i
#       - run:
#           name: Copy code to server
#           command: sudo apt install rsync 
#                    rsync -v . ubuntu@54.83.108.237:/home/ubuntu/node/
      - run:
          name: ssh
          command: | 
            ssh -o StrictHostKeyChecking=no ubuntu@54.83.108.237 \
            cd  circleci-node-deploy
            npm i
            mkdir test
            npm install pm2@latest -g
            pm2 start app.js
