version: 2.1

workflows:
  test-deploy:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: cimg/node:14.13.0
    steps:
      - checkout
      - run: 
          name: Install dependences
          command: npm i
      - run: |
            ssh -o StrictHostKeyChecking=no ubuntu@54.83.108.237 \
            npm i        
          #  pm2 start app.js
